name: motivationbuddies
favicon: null
layout_spectrum: 0.9753153759520501
typography_spectrum: 0.929070774000138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2541833824943751
  lightness: 0.13737552240490913
  saturation: 0.9389881331007928
  rhythmicContrast: 0.8490367410704494
purpose: []
